FROM node:20-slim
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /app
COPY package.json ./
RUN npm config set registry https://registry.npmmirror.com && \
    npm install

COPY . .
RUN npx prisma generate
EXPOSE 5000
CMD ["npm", "run", "dev"]
