FROM node:20-slim
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /app
COPY package.json ./
RUN npm install -g pnpm && \
    pnpm config set registry https://registry.npmmirror.com && \
    pnpm config set verify-store-integrity false && \
    pnpm install --ignore-scripts
COPY . .
RUN pnpm prisma generate
EXPOSE 5000
CMD ["pnpm", "run", "dev"]
